spring.profiles: dev

logging.level:
  org.kafkatriage: DEBUG
#  org.apache.kafka.clients.consumer.KafkaConsumer: DEBUG
#  org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: DEBUG
#  org.apache.kafka.clients.producer.KafkaProducer: DEBUG
#  org.hibernate: DEBUG
  org.hibernate.stat: debug
#  org.hibernate.resource.jdbc.internal: TRACE
#  org.springframework.transaction: TRACE

management:
  endpoints.web.exposure.include: "*"

spring:
  datasource:
    initialization-mode: always
    password:
    platform: dev
    url: jdbc:postgresql://localhost/kafka-triage
    username: kafka-triage
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
